services:
  db:
    image: postgres:17-alpine
    container_name: lensee_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lensee
      POSTGRES_USER: lensee_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-SomeStrongPassword123!}
    ports:
      - "8181:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lensee_user -d lensee"]
      interval: 10s
      timeout: 5s
      retries: 5

  lensee.host:
    image: ${DOCKER_REGISTRY-}lenseehost
    build:
      context: .
      dockerfile: backend/Lensee.Host/Dockerfile
    container_name: lensee_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=lensee;Username=lensee_user;Password=${DB_PASSWORD:-SomeStrongPassword123!}
      Jwt__Secret: ${JWT_SECRET:-x7kP9mQw2nRjLvBsYdHcZeAuFgTiWoNp}
      Jwt__Issuer: Lensee
      Jwt__Audience: Lensee.App
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lensee_web
    restart: unless-stopped
    depends_on:
      - lensee.host
    ports:
      - "3000:80"

volumes:
  pgdata:
